### PR TITLE
Update to 2.14.4

### PR DESCRIPTION
**Pull request by basjanssen**
- Bumped version to 2.14.4
- Updated the snippet https://raw.githubusercontent.com/rollbar/rollbar.js/master/dist/rollbar.snippet.js
- Generated the min/map using grunt

### CODE REVIEW

**Comment by basjanssen** [comment]
@tandibar I think I have done all the steps to create a PR for a new release. Do you have time to check it out?

**Comment by jpike88** [comment]
I've since moved to angular 2.

want to be able to publish the npm module yourself?

**Comment by basjanssen** [comment]
I do not know how, but if you want me to do it, I can figure it out 👍

**Comment by jpike88** [comment]
create an account on npmjs.com and I'll hand the package over to you

**Comment by basjanssen** [comment]
https://www.npmjs.com/~basjanssen

**Comment by basjanssen** [comment]
@jpike88 I am somewhat linked to ng-rollbar on npmjs, but I cannot publish anything. I did login using `npm adduser` I'm also not sure why it says ng-rollbar@2.4.2 instead of 2.14.4
```
➜  ng-rollbar git:(master) npm publish
npm notice
npm notice 📦  ng-rollbar@2.4.2
npm notice === Tarball Contents ===
npm notice 968B   package.json
npm notice 478B   bower.json
npm notice 4.4kB  Gruntfile.js
npm notice 68B    index.js
npm notice 1.9kB  karma.conf.js
npm notice 9.9kB  ng-rollbar.js
npm notice 8.0kB  ng-rollbar.min.js
npm notice 9.2kB  ng-rollbar.min.js.map
npm notice 5.3kB  README.md
npm notice 291B   .idea/misc.xml
npm notice 272B   .idea/modules.xml
npm notice 363B   .idea/ng-rollbar.iml
npm notice 180B   .idea/vcs.xml
npm notice 11.1kB .idea/workspace.xml
npm notice 2.3kB  test/module.spec.js
npm notice 6.5kB  test/rollbar.spec.js
npm notice === Tarball Details ===
npm notice name:          ng-rollbar
npm notice version:       2.4.2
npm notice package size:  17.7 kB
npm notice unpacked size: 61.3 kB
npm notice shasum:        c945b20e5814b2a33743ec93a26ec7e4f413a259
npm notice integrity:     sha512-pwYLlcwYNQrU8[...]D45FaXHadSpXA==
npm notice total files:   16
npm notice
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You do not have permission to publish "ng-rollbar". Are you logged in as the correct user? : ng-rollbar

npm ERR! A complete log of this run can be found in:
```

**Comment by jpike88** [comment]
it says you're logged in ng-rollbar?? shouldn't you be logged in as basjanssen?

**Comment by basjanssen** [comment]
I think that's weird as well, but I cannot change that :/
```
➜  ng-rollbar git:(master) ✗ npm whoami
basjanssen
➜  ng-rollbar git:(master) ✗ npm adduser
Username: basjanssen
Password:
Email: (this IS public) bas.janssen@nedap.com
Logged in as basjanssen on https://registry.npmjs.org/.
➜  ng-rollbar git:(master) ✗ npm publish
npm notice
npm notice 📦  ng-rollbar@2.14.4
npm notice === Tarball Contents ===
npm notice 1.0kB  package.json
npm notice 479B   bower.json
npm notice 4.4kB  Gruntfile.js
npm notice 68B    index.js
npm notice 1.9kB  karma.conf.js
npm notice 10.7kB ng-rollbar.js
npm notice 8.0kB  ng-rollbar.min.js
npm notice 9.1kB  ng-rollbar.min.js.map
npm notice 5.3kB  README.md
npm notice 291B   .idea/misc.xml
npm notice 272B   .idea/modules.xml
npm notice 363B   .idea/ng-rollbar.iml
npm notice 180B   .idea/vcs.xml
npm notice 12.5kB .idea/workspace.xml
npm notice 2.3kB  test/module.spec.js
npm notice 6.5kB  test/rollbar.spec.js
npm notice === Tarball Details ===
npm notice name:          ng-rollbar
npm notice version:       2.14.4
npm notice package size:  18.0 kB
npm notice unpacked size: 63.3 kB
npm notice shasum:        575cab25ae666f237ec202879f2f45ea83afca9b
npm notice integrity:     sha512-lUkpl1RA6VobF[...]MDOIk41jQA9wQ==
npm notice total files:   16
npm notice
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You do not have permission to publish "ng-rollbar". Are you logged in as the correct user? : ng-rollbar

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bas.janssen/.npm/_logs/2020-02-12T16_10_47_658Z-debug.log
➜  ng-rollbar git:(master) ✗
```

**Comment by basjanssen** [comment]
Ah, after updating npm
```
➜  ng-rollbar git:(master) ✗ npm publish
npm notice
npm notice 📦  ng-rollbar@2.14.4
npm notice === Tarball Contents ===
npm notice 363B   .idea/ng-rollbar.iml
npm notice 4.4kB  Gruntfile.js
npm notice 68B    index.js
npm notice 1.9kB  karma.conf.js
npm notice 2.3kB  test/module.spec.js
npm notice 10.7kB ng-rollbar.js
npm notice 8.0kB  ng-rollbar.min.js
npm notice 6.5kB  test/rollbar.spec.js
npm notice 479B   bower.json
npm notice 1.0kB  package.json
npm notice 9.1kB  ng-rollbar.min.js.map
npm notice 5.3kB  README.md
npm notice 291B   .idea/misc.xml
npm notice 272B   .idea/modules.xml
npm notice 180B   .idea/vcs.xml
npm notice 12.5kB .idea/workspace.xml
npm notice === Tarball Details ===
npm notice name:          ng-rollbar
npm notice version:       2.14.4
npm notice package size:  18.1 kB
npm notice unpacked size: 63.3 kB
npm notice shasum:        8a9e3ceab2a4e58dc779e3e5cee5495e0dd545d2
npm notice integrity:     sha512-/d/oRkNoOO5/d[...]8i/UCB8+EV07g==
npm notice total files:   16
npm notice
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/ng-rollbar - You do not have permission to publish "ng-rollbar". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
```

**Comment by basjanssen** [comment]
@jpike88 Do you know how to handle this? Can you maybe try to publish it?

**Pull request merged**
