### PR TITLE
Bind the service's Rollbar helper methods to their counterparts on the native Rollbar object

### PR DESCRIPTION
**Pull request by nrutman**
Rollbar's helper methods (`critical`, `error`, `warning`, `info`, etc.) allow multiple parameters such as explicit Exception objects and callback methods. So for instance the following code would log an error to Rollbar and then display an alert:

``` javascript
Rollbar.error('This was an error!', function() {
    alert('The error has been logged.');
});
```

However, with the way the methods were bound to the Angular service, only the very first parameter was getting passed through to the `window.Rollbar` object. So while the above works with the native Rollbar JS snippet, the alert will never fire when using `ng-rollbar`.

This PR binds any native Rollbar methods to the correct method on the Rollbar object and passes in any and all arguments that are passed to it. This allows full use of the Rollbar JS API through the `ng-rollbar` module. This creates a true "pass-through" and future-proofs the interface between `ng-rollbar` and the native `Rollbar` object.

### CODE REVIEW

**Comment by nrutman** [comment]
@tandibar, do you have any questions or suggestions with this PR?

**Comment by nrutman** [comment]
I'm trying to properly generate the minified source (so this PR is more accurate), but I'm having some problems with the grunt build. Here's what I'm getting:

```
> grunt update-lib:1.9.1

Running "update-lib:1.9.1" (update-lib) task
starting update-lib with version: 1.9.1
requesting 'https://raw.githubusercontent.com/rollbar/rollbar.js/v1.9.1/dist/rollbar.snippet.js' ...
Got response: 200
found /* rollbar client lib start */
inserting new lib snippet
found /* rollbar client lib end */
overwriting ng-rollbar.js with new lib

Running "gitcommit:lib-update" (gitcommit) task
Warning:  Use --force to continue.

Aborted due to warnings.
```

What am I doing wrong? Self-disclosure: I'm much more familiar with gulp than grunt...so this is a little unfamiliar to me.

**Comment by tandibar** [comment]
I can't see any error or warning. So i am not sure what the problem is. But you should not generate a new release in the PR. You PR is just fine, i will roll out a new release after the merge.
Your PR seems very reasonable and i was just a few days out of office, that is why there was no response.
Thank U very much.

**Comment by nrutman** [comment]
@tandibar, excellent. Thanks so much!

**Comment by didlich** [comment]
@nrutman I tested your RP right now, it doesn't work for me

I use 
   Rollbar.error("Test Rollbar Error");
with your version the error reported by Rollbar ist "error" but not "Test Rollbar Error"

with your version the following is also not working:

```
Rollbar.configure({
        payload: {
          message: info,
          client: info
        }
      });
```

if I change your _bindRollbarMethod to this:

```
function _bindRollbarMethod(methodName) {
  return function() {
    var args = arguments;
    $window.Rollbar[methodName].apply($window.Rollbar, args);
};
```

then the error Reported by Rollbar is "Test Rollbar Error"

please, could you test your RP to verify this

**Comment by nrutman** [comment]
@didlich, you're exactly right. The branch / PR is fixed and tested. Thanks for the heads-up.

**Pull request merged**
