### PR TITLE
UPGRADE: rollbar-2.4.2

### PR DESCRIPTION
**Pull request by grzegorzblaszczyk**
UPGRADE: rollbar-2.4.2

### CODE REVIEW

**Comment by chriscodeweb** [comment]
Hi Grzegorz Błaszczyk, do you know when you can merged this so that 2.4.2 will be available in yarn?

**Comment by grzegorzblaszczyk** [comment]
@chriscodeweb It depends on @tandibar .

**Comment by pamo** [comment]
Isn't this a duplicate of  #50?

**Comment by grzegorzblaszczyk** [comment]
@pamo Yes, it is - I was asked by @chriscodeweb to upgrade to the newest version, so I did. 

@tandibar Please merge #50 and close this PR.

**Pull request merged**
